#spring:
#  datasource:
#    url: ${DATASOURCE_URL}
#    username: ${DATASOURCE_USERNAME}
#    password: ${DATASOURCE_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver

# Oracle Cloud DataSource는 OracleCloudConfig에서 직접 생성
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@dinkdb_medium
#    username: DA2504
#    password: Data2504
#    driver-class-name: oracle.jdbc.OracleDriver
#    hikari:
#      maximum-pool-size: 5
#      connection-timeout: 30000
#      idle-timeout: 600000
#      max-lifetime: 1800000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

