server:
  port: 8080

spring:
  application:
    name: kftc
  config:
    import: application-datasource.yml, application-setting.yml, application-local.yml
  profiles:
    active: datasource, setting, local

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.kftc: DEBUG

